// Cernum development benchmark · Pass 1 — the specification, the fixture, and the scoring contract.
//
// Nothing in this file runs a model. It proves that the machinery a development measurement rests on
// is deterministic, fail-closed, and SEPARATE from the text benchmark whose identity is sealed
// against the parity corpus.

import { describe, expect, it } from 'vitest';

import {
  FixtureRepo, FixtureRepoValidationFailure, diffSnapshots, fixtureRepoDigest, makeFixtureRepo,
  snapshotDigest, snapshotOf, snapshotPaths, touchedPaths, validateFixtureRepo,
} from '../../src/core/development-fixture';
import { ledgerlite, developmentFixtureRepos } from '../../src/core/development-fixtures/ledgerlite';
import {
  AssertionContext, DevelopmentAssertion, assertionsDigest, codeContainsPhrase, evaluateAssertions,
  evaluatePredicate, normalizeCode, resolveJSONPointer,
} from '../../src/core/development-assertions';
import {
  DEVELOPMENT_METRICS, DEVELOPMENT_SCORING_CONTRACT_ID, DEVELOPMENT_SCORING_CONTRACT_VERSION,
  EXECUTED_TIER_NOT_MEASURED_REASON, MINIMUM_REQUIRED_FILES_FOR_MULTI_FILE_EDIT,
  METRIC_SPEC_BY_ID, ALL_DEVELOPMENT_DIMENSIONS, developmentContractDigest, gradeTask,
  isDevelopmentMetricID, metricsForDimension, referencedMetrics,
} from '../../src/core/development-scoring';
import {
  DEVELOPMENT_ANSWER_PATH, DevelopmentSuite, DevelopmentTask, DevelopmentValidationFailure,
  developmentComparabilityKey, developmentSuiteDigest, developmentTaskDigest, makeDevelopmentSuite,
  makeDevelopmentTask, provenanceIsComplete, validateDevelopmentSuite,
} from '../../src/core/development-benchmark';
import { ALL_DIMENSIONS } from '../../src/core/evaluation';
import { allGovernedSuites, registeredSuites } from '../../src/core/catalog';

// The fixture as sealed at authoring time. A change to any byte of `ledgerlite` changes this, and a
// change to the fixture under a task that did not change is exactly what the drift check catches.
const LEDGERLITE_DIGEST = 'mldr1:69aebcb7bc9d6d03';
const CONTRACT_DIGEST = 'mldc1:cafc30af44a5f467';

describe('the ledgerlite fixture repository', () => {
  it('validates, and seals to the digest the tasks are written against', () => {
    expect(() => validateFixtureRepo(ledgerlite)).not.toThrow();
    expect(fixtureRepoDigest(ledgerlite)).toBe(LEDGERLITE_DIGEST);
    expect(developmentFixtureRepos).toContain(ledgerlite);
  });

  it('carries the three traps the repository-understanding suite depends on', () => {
    const byPath = new Map(ledgerlite.files.map((file) => [file.path, file]));

    // Trap 1: the public surface forwards. A shallow search for `createCharge` finds the facade.
    expect(byPath.get('src/api/charges.js')!.contents).toContain('runChargePipeline');
    expect(byPath.get('src/core/charge-pipeline.js')!.contents).toContain('function runChargePipeline');

    // Trap 2: the generated module declares its source, and the fixture says so structurally.
    const generated = byPath.get('src/schema/generated/charge-fields.js')!;
    expect(generated.role).toBe('generated');
    expect(generated.generatedFrom).toBe('src/schema/charge.schema.json');
    expect(generated.contents).toContain('DO NOT EDIT THIS FILE BY HAND');

    // Trap 3: rounding goes through Math.round and no golden case is negative.
    expect(byPath.get('src/util/money.js')!.contents).toContain('Math.round');
    const table = JSON.parse(byPath.get('test/cases/rounding.cases.json')!.contents) as { cases: { amount: number }[] };
    expect(table.cases.every((entry) => entry.amount > 0)).toBe(true);
  });

  it('is internally consistent: the generated field list agrees with the schema it names', () => {
    // The invariant the multi-file-edit suite is built on. A candidate that adds a field to the
    // schema and does not regenerate the derived module breaks exactly this, and it is checkable
    // from the bytes alone — no generator has to be run to see the disagreement.
    const byPath = new Map(ledgerlite.files.map((file) => [file.path, file.contents]));
    const schema = JSON.parse(byPath.get('src/schema/charge.schema.json')!) as {
      fields: { name: string; required: boolean }[];
    };
    const generated = byPath.get('src/schema/generated/charge-fields.js')!;
    const readArray = (name: string): string[] =>
      JSON.parse(new RegExp(`const ${name} = (\\[[^\\]]*\\]);`).exec(generated)![1]) as string[];

    expect(readArray('CHARGE_FIELDS')).toEqual(schema.fields.map((field) => field.name));
    expect(readArray('REQUIRED_CHARGE_FIELDS')).toEqual(schema.fields.filter((field) => field.required).map((field) => field.name));
  });

  it('declares every file with a role, and only a generated file names a producer', () => {
    for (const file of ledgerlite.files) {
      expect(file.contents.length).toBeGreaterThan(0);
      if (file.role !== 'generated') expect(file.generatedFrom).toBeUndefined();
    }
    expect(ledgerlite.files.filter((file) => file.role === 'generated')).toHaveLength(1);
    expect(ledgerlite.files.some((file) => file.role === 'test')).toBe(true);
    expect(ledgerlite.files.some((file) => file.role === 'tooling')).toBe(true);
  });
});

describe('fixture repository validation is fail-closed', () => {
  const base = (files: FixtureRepo['files']): FixtureRepo =>
    makeFixtureRepo({ id: 'fixture.repo.probe', version: '1', title: 'probe', summary: 'probe', files });

  const ok = { path: 'src/a.js', role: 'source' as const, contents: 'x' };

  it('refuses a path that is not a plain POSIX-relative path', () => {
    for (const path of ['/etc/passwd', '../escape.js', './a.js', 'a\\b.js', 'a//b.js']) {
      expect(() => validateFixtureRepo(base([{ ...ok, path }])), path).toThrow(FixtureRepoValidationFailure);
    }
  });

  it('refuses a duplicate path, an empty file, and a repository with no source', () => {
    expect(() => validateFixtureRepo({ ...base([ok]), files: [ok, ok] })).toThrow(/twice/);
    expect(() => validateFixtureRepo(base([{ ...ok, contents: '' }]))).toThrow(/no contents/);
    expect(() => validateFixtureRepo(base([{ path: 'README.md', role: 'doc', contents: 'x' }]))).toThrow(/no source file/);
  });

  it('refuses a generated file with no source, a missing source, or a self-reference', () => {
    expect(() => validateFixtureRepo(base([ok, { path: 'g.js', role: 'generated', contents: 'x' }]))).toThrow(/names no source/);
    expect(() => validateFixtureRepo(base([ok, { path: 'g.js', role: 'generated', generatedFrom: 'nope.json', contents: 'x' }]))).toThrow(/does not contain/);
    expect(() => validateFixtureRepo(base([ok, { path: 'g.js', role: 'generated', generatedFrom: 'g.js', contents: 'x' }]))).toThrow(/generated from itself/);
  });

  it('refuses a non-generated file that names a producer', () => {
    expect(() => validateFixtureRepo(base([{ ...ok, generatedFrom: 'src/a.js' }]))).toThrow(/only a generated file/);
  });

  it('refuses an empty repository and one with no id or version', () => {
    expect(() => validateFixtureRepo(base([]))).toThrow(/no files/);
    expect(() => validateFixtureRepo({ ...base([ok]), id: '' })).toThrow(/no id/);
    expect(() => validateFixtureRepo({ ...base([ok]), version: '' })).toThrow(/no version/);
  });
});

describe('snapshots and differences', () => {
  const baseline = snapshotOf(ledgerlite);

  it('seals a snapshot and orders its paths deterministically', () => {
    expect(snapshotDigest(baseline)).toBe('mldsnap1:aa43e94dc603411');
    expect(snapshotPaths(baseline)).toEqual([...snapshotPaths(baseline)].sort());
    expect(snapshotPaths(baseline)).toHaveLength(17);
  });

  it('classifies every path as added, removed, modified or unchanged, and nothing twice', () => {
    const result = new Map(baseline);
    result.set('src/util/money.js', 'changed');
    result.set('src/util/rounding.js', 'new');
    result.delete('CHANGELOG.md');

    const difference = diffSnapshots(baseline, result);
    expect(difference.added).toEqual(['src/util/rounding.js']);
    expect(difference.removed).toEqual(['CHANGELOG.md']);
    expect(difference.modified).toEqual(['src/util/money.js']);
    expect(difference.unchanged).toHaveLength(15);
    expect(touchedPaths(difference)).toEqual(['CHANGELOG.md', 'src/util/money.js', 'src/util/rounding.js']);

    const all = [...difference.added, ...difference.removed, ...difference.modified, ...difference.unchanged];
    expect(new Set(all).size).toBe(all.length);
  });

  it('reports an untouched repository as entirely unchanged', () => {
    const difference = diffSnapshots(baseline, new Map(baseline));
    expect(touchedPaths(difference)).toEqual([]);
    expect(difference.unchanged).toHaveLength(17);
  });
});

describe('the assertion predicate language', () => {
  const baseline: AssertionContext['baseline'] = new Map([
    ['a.json', '{"fields":["amount","region"],"nested":{"deep":[1,2]}}'],
    ['b.js', 'function total() { return 1; }\n'],
    ['c.md', 'untouched\n'],
  ]);
  const context = (result: Map<string, string>): AssertionContext => ({ baseline, result });
  const unchanged = () => context(new Map(baseline));

  it('decides existence and absence', () => {
    expect(evaluatePredicate({ kind: 'fileExists', path: 'b.js' }, unchanged()).held).toBe(true);
    expect(evaluatePredicate({ kind: 'fileExists', path: 'nope' }, unchanged()).held).toBe(false);
    expect(evaluatePredicate({ kind: 'fileAbsent', path: 'nope' }, unchanged()).held).toBe(true);
    expect(evaluatePredicate({ kind: 'fileAbsent', path: 'b.js' }, unchanged()).held).toBe(false);
  });

  it('decides changed and unchanged against the baseline, and calls a deletion a failure to preserve', () => {
    const edited = new Map(baseline);
    edited.set('b.js', 'function total() { return 2; }\n');
    expect(evaluatePredicate({ kind: 'changedFromBaseline', path: 'b.js' }, context(edited)).held).toBe(true);
    expect(evaluatePredicate({ kind: 'unchangedFromBaseline', path: 'b.js' }, context(edited)).held).toBe(false);
    expect(evaluatePredicate({ kind: 'unchangedFromBaseline', path: 'c.md' }, context(edited)).held).toBe(true);

    const deleted = new Map(baseline);
    deleted.delete('c.md');
    const verdict = evaluatePredicate({ kind: 'unchangedFromBaseline', path: 'c.md' }, context(deleted));
    expect(verdict.held).toBe(false);
    expect(verdict.detail).toMatch(/deleted/);

    // An added file counts as changed; a file that never arrived does not.
    const added = new Map(baseline);
    added.set('new.js', 'x');
    expect(evaluatePredicate({ kind: 'changedFromBaseline', path: 'new.js' }, context(added)).held).toBe(true);
    expect(evaluatePredicate({ kind: 'changedFromBaseline', path: 'new.js' }, unchanged()).held).toBe(false);
  });

  it('fences scope with onlyTheseTouched, and names every path that strayed', () => {
    const strayed = new Map(baseline);
    strayed.set('b.js', 'edited');
    strayed.set('c.md', 'also edited');
    const verdict = evaluatePredicate({ kind: 'onlyTheseTouched', paths: ['b.js'] }, context(strayed));
    expect(verdict.held).toBe(false);
    expect(verdict.detail).toContain('c.md');
    expect(evaluatePredicate({ kind: 'onlyTheseTouched', paths: ['b.js', 'c.md'] }, context(strayed)).held).toBe(true);
  });

  it('matches phrases on code terms rather than on prose-folded text', () => {
    expect(normalizeCode('A  \t B')).toBe('a b');
    expect(codeContainsPhrase('charge.currency = x', 'charge.currency')).toBe(true);
    // The prose normalizer folds punctuation; this one must not, or an assertion naming an
    // expression would match text that does not contain that expression.
    expect(codeContainsPhrase('charge_currency = x', 'charge.currency')).toBe(false);
    expect(codeContainsPhrase('CHARGE.Currency', 'charge.currency')).toBe(true);
  });

  it('decides containsPhrase, lacksPhrase, matches and occursAtLeast', () => {
    const result = unchanged();
    expect(evaluatePredicate({ kind: 'containsPhrase', path: 'b.js', phrase: 'function total' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'lacksPhrase', path: 'b.js', phrase: 'TODO' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'lacksPhrase', path: 'b.js', phrase: 'return 1' }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'matches', path: 'b.js', pattern: 'function\\s+total' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'occursAtLeast', path: 'b.js', pattern: 'return', minimum: 1 }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'occursAtLeast', path: 'b.js', pattern: 'return', minimum: 2 }, result).held).toBe(false);
  });

  it('treats an absent file as unable to satisfy a positive predicate and unable to violate a negative one', () => {
    const result = unchanged();
    expect(evaluatePredicate({ kind: 'containsPhrase', path: 'gone', phrase: 'x' }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'lacksPhrase', path: 'gone', phrase: 'x' }, result).held).toBe(true);
  });

  it('reports an uncompilable fixture pattern as a fixture defect rather than throwing mid-campaign', () => {
    const verdict = evaluatePredicate({ kind: 'matches', path: 'b.js', pattern: '([' }, unchanged());
    expect(verdict.held).toBe(false);
    expect(verdict.detail).toMatch(/fixture defect/);
  });

  it('reads JSON by pointer, including array indices and escapes', () => {
    const document = JSON.parse(baseline.get('a.json')!);
    expect(resolveJSONPointer(document, '')).toEqual(document);
    expect(resolveJSONPointer(document, '/fields/0')).toBe('amount');
    expect(resolveJSONPointer(document, '/nested/deep/1')).toBe(2);
    expect(resolveJSONPointer(document, '/fields/9')).toBeUndefined();
    expect(resolveJSONPointer(document, '/missing')).toBeUndefined();
    expect(resolveJSONPointer(document, 'fields')).toBeUndefined();
    expect(resolveJSONPointer({ 'a/b': 1, 'c~d': 2 }, '/a~1b')).toBe(1);
    expect(resolveJSONPointer({ 'a/b': 1, 'c~d': 2 }, '/c~0d')).toBe(2);
  });

  it('decides the JSON predicates, and says so when the file does not parse', () => {
    const result = unchanged();
    expect(evaluatePredicate({ kind: 'parsesAsJSON', path: 'a.json' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'parsesAsJSON', path: 'b.js' }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'jsonEquals', path: 'a.json', pointer: '/fields', value: ['amount', 'region'] }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'jsonEquals', path: 'a.json', pointer: '/fields', value: ['region', 'amount'] }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'jsonContains', path: 'a.json', pointer: '/fields', value: 'region' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'jsonContains', path: 'a.json', pointer: '/fields', value: 'currency' }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'jsonExcludes', path: 'a.json', pointer: '/fields', value: 'currency' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'jsonExcludes', path: 'a.json', pointer: '/fields', value: 'region' }, result).held).toBe(false);
    expect(evaluatePredicate({ kind: 'jsonHasPointer', path: 'a.json', pointer: '/nested' }, result).held).toBe(true);
    expect(evaluatePredicate({ kind: 'jsonLacksPointer', path: 'a.json', pointer: '/nope' }, result).held).toBe(true);

    const broken = evaluatePredicate({ kind: 'jsonEquals', path: 'b.js', pointer: '/x', value: 1 }, result);
    expect(broken.held).toBe(false);
    expect(broken.detail).toMatch(/does not parse as JSON/);
  });

  it('compares JSON values structurally rather than by key order', () => {
    const result = context(new Map([['a.json', '{"o":{"b":2,"a":1}}']]));
    expect(evaluatePredicate({ kind: 'jsonEquals', path: 'a.json', pointer: '/o', value: { a: 1, b: 2 } }, result).held).toBe(true);
  });

  it('evaluates an assertion set in a stable order and preserves every label', () => {
    const assertions: DevelopmentAssertion[] = [
      { id: 'z', purpose: 'p', metric: 'answerAccuracy', visibility: 'heldOut', predicate: { kind: 'fileExists', path: 'b.js' } },
      { id: 'a', purpose: 'p', metric: 'answerAccuracy', visibility: 'stated', predicate: { kind: 'fileExists', path: 'nope' }, shortcutProbe: true },
    ];
    const outcomes = evaluateAssertions(assertions, unchanged());
    expect(outcomes.map((outcome) => outcome.id)).toEqual(['a', 'z']);
    expect(outcomes[0]).toMatchObject({ held: false, shortcutProbe: true, visibility: 'stated', metric: 'answerAccuracy' });
    expect(outcomes[1]).toMatchObject({ held: true, shortcutProbe: false, visibility: 'heldOut' });
    expect(outcomes.every((outcome) => outcome.detail.length > 0)).toBe(true);
  });

  it('seals an assertion set independently of the order it was written in', () => {
    const one: DevelopmentAssertion = { id: 'one', purpose: 'p', metric: 'answerAccuracy', visibility: 'heldOut', predicate: { kind: 'fileExists', path: 'x' } };
    const two: DevelopmentAssertion = { id: 'two', purpose: 'p', metric: 'answerAccuracy', visibility: 'stated', predicate: { kind: 'fileAbsent', path: 'y' } };
    expect(assertionsDigest([one, two])).toBe(assertionsDigest([two, one]));
    expect(assertionsDigest([one])).not.toBe(assertionsDigest([one, two]));
  });
});

describe('the development scoring contract', () => {
  it('seals to a pinned digest, so a silent change to a metric table is visible', () => {
    expect(developmentContractDigest()).toBe(CONTRACT_DIGEST);
    expect(DEVELOPMENT_SCORING_CONTRACT_ID).toBe('contract.cernum.development');
    expect(DEVELOPMENT_SCORING_CONTRACT_VERSION).toBe('1');
  });

  it('covers both dimensions, and gives every metric a tier, a bar and a summary', () => {
    expect(ALL_DEVELOPMENT_DIMENSIONS).toEqual(['repositoryUnderstanding', 'multiFileEditing']);
    for (const dimension of ALL_DEVELOPMENT_DIMENSIONS) expect(metricsForDimension(dimension).length).toBeGreaterThan(0);
    for (const spec of DEVELOPMENT_METRICS) {
      expect(spec.summary.length).toBeGreaterThan(0);
      expect(spec.passBarMilli).toBeGreaterThan(0);
      expect(METRIC_SPEC_BY_ID.get(spec.id)).toBe(spec);
      expect(isDevelopmentMetricID(spec.id)).toBe(true);
    }
    expect(isDevelopmentMetricID('conversation')).toBe(false);
    expect(new Set(DEVELOPMENT_METRICS.map((spec) => spec.id)).size).toBe(DEVELOPMENT_METRICS.length);
  });

  it('names every dimension the brief asked for', () => {
    const ids = DEVELOPMENT_METRICS.map((spec) => spec.id);
    for (const required of [
      'correctFilesEdited', 'requiredFilesPresent', 'unrelatedFilesUntouched', 'implementationCorrectness',
      'testsAddedOrUpdated', 'existingTestsPreserved', 'newTestsPass', 'buildSucceeds', 'churnRestraint', 'retryBehaviour',
    ]) expect(ids, required).toContain(required);
  });

  it('keeps the executed tier declared, gating, and empty of structural assertions', () => {
    const executed = DEVELOPMENT_METRICS.filter((spec) => spec.tier === 'executed');
    expect(executed.map((spec) => spec.id)).toEqual(['newTestsPass', 'existingTestsPass', 'buildSucceeds']);
    expect(executed.every((spec) => spec.gating)).toBe(true);
  });

  it('collects the metrics an assertion set references', () => {
    expect(referencedMetrics([
      { id: 'b', purpose: 'p', metric: 'answerAccuracy', visibility: 'stated', predicate: { kind: 'fileExists', path: 'x' } },
      { id: 'a', purpose: 'p', metric: 'omissionAvoidance', visibility: 'heldOut', predicate: { kind: 'fileExists', path: 'x' } },
      { id: 'c', purpose: 'p', metric: 'answerAccuracy', visibility: 'heldOut', predicate: { kind: 'fileExists', path: 'x' } },
    ])).toEqual(['answerAccuracy', 'omissionAvoidance']);
  });
});

describe('grading one attempt', () => {
  const outcome = (id: string, metric: string, held: boolean, extra: Partial<{ visibility: 'stated' | 'heldOut'; shortcutProbe: boolean }> = {}) => ({
    id, metric, held, detail: `${id} ${held ? 'held' : 'did not hold'}`,
    visibility: extra.visibility ?? ('heldOut' as const), shortcutProbe: extra.shortcutProbe ?? false,
  });

  const everyStructuralMetricHolding = metricsForDimension('multiFileEditing')
    .filter((spec) => spec.tier === 'structural' && spec.id !== 'retryBehaviour')
    .map((spec) => outcome(`ok-${spec.id}`, spec.id, true));

  it('never awards full credit while the executed tier is unmeasured', () => {
    const grade = gradeTask('multiFileEditing', everyStructuralMetricHolding);
    expect(grade.structuralCredit).toBe('full');
    expect(grade.executedCredit).toBe('notMeasured');
    expect(grade.credit).toBe('partial');
    expect(grade.creditReason).toContain('newTestsPass');
    expect(grade.creditReason).toContain('no OS sandbox');
  });

  it('reports an executed metric as not measured with a reason, never as a zero', () => {
    const grade = gradeTask('multiFileEditing', everyStructuralMetricHolding);
    for (const id of ['newTestsPass', 'existingTestsPass', 'buildSucceeds'] as const) {
      const result = grade.metrics.find((metric) => metric.id === id)!;
      expect(result.status).toBe('notMeasured');
      expect(result.valueMilli).toEqual({ unavailableReason: EXECUTED_TIER_NOT_MEASURED_REASON });
      expect('measured' in result.valueMilli).toBe(false);
    }
  });

  it('fails the gate when a required file was omitted, however good the rest is', () => {
    const outcomes = everyStructuralMetricHolding.map((entry) =>
      entry.metric === 'requiredFilesPresent' ? { ...entry, held: false } : entry);
    const grade = gradeTask('multiFileEditing', outcomes);
    expect(grade.structuralCredit).toBe('partial');
    expect(grade.credit).toBe('partial');
    expect(grade.metrics.find((metric) => metric.id === 'requiredFilesPresent')!.status).toBe('fail');
    expect(grade.creditReason).toContain('requiredFilesPresent');
  });

  it('gives a metric with no assertion notApplicable rather than a free pass', () => {
    const grade = gradeTask('multiFileEditing', [outcome('only', 'correctFilesEdited', true)]);
    const untested = grade.metrics.find((metric) => metric.id === 'implementationCorrectness')!;
    expect(untested.status).toBe('notApplicable');
    expect(untested.valueMilli).toEqual({ unavailableReason: 'this task declares no assertion for this metric' });
    expect(grade.structuralCredit).toBe('full');
  });

  it('reports none when no gating structural metric was decided at all', () => {
    const grade = gradeTask('multiFileEditing', []);
    expect(grade.structuralCredit).toBe('none');
    expect(grade.credit).toBe('none');
  });

  it('computes a metric rate over its own assertions only', () => {
    const grade = gradeTask('repositoryUnderstanding', [
      outcome('a', 'answerAccuracy', true),
      outcome('b', 'answerAccuracy', false),
      outcome('c', 'omissionAvoidance', true),
    ]);
    const accuracy = grade.metrics.find((metric) => metric.id === 'answerAccuracy')!;
    expect(accuracy.valueMilli).toEqual({ measured: 500 });
    expect(accuracy.status).toBe('fail');
    expect(accuracy.assertionIDs).toEqual(['a', 'b']);
    expect(accuracy.detail).toContain('b did not hold');
    expect(grade.metrics.find((metric) => metric.id === 'omissionAvoidance')!.valueMilli).toEqual({ measured: 1_000 });
  });

  it('separates a suspected shortcut from a lost point', () => {
    const clean = gradeTask('multiFileEditing', everyStructuralMetricHolding);
    expect(clean.shortcutSuspected).toBe(false);
    expect(clean.shortcutReasons).toEqual([]);

    const probed = gradeTask('multiFileEditing', [
      ...everyStructuralMetricHolding,
      outcome('hardcoded', 'implementationCorrectness', false, { shortcutProbe: true }),
    ]);
    expect(probed.shortcutSuspected).toBe(true);
    expect(probed.shortcutReasons[0]).toContain('hardcoded');
  });

  it('reports the held-out rate over held-out assertions only', () => {
    const grade = gradeTask('repositoryUnderstanding', [
      outcome('stated-pass', 'answerAccuracy', true, { visibility: 'stated' }),
      outcome('held-pass', 'answerAccuracy', true, { visibility: 'heldOut' }),
      outcome('held-fail', 'answerAccuracy', false, { visibility: 'heldOut' }),
    ]);
    expect(grade.heldOutPassRateMilli).toEqual({ measured: 500 });

    const noneHeldOut = gradeTask('repositoryUnderstanding', [outcome('s', 'answerAccuracy', true, { visibility: 'stated' })]);
    expect(noneHeldOut.heldOutPassRateMilli).toEqual({ unavailableReason: 'this task declares no held-out assertion' });
  });

  it('records retry behaviour when the runner supplied it, and not measured when it did not', () => {
    expect(gradeTask('multiFileEditing', everyStructuralMetricHolding).metrics
      .find((metric) => metric.id === 'retryBehaviour')!.status).toBe('notMeasured');
    expect(gradeTask('multiFileEditing', everyStructuralMetricHolding, { retryDetail: 'one retry, converged' }).metrics
      .find((metric) => metric.id === 'retryBehaviour')!.detail).toBe('one retry, converged');
  });

  it('never reports a metric from the other dimension', () => {
    const grade = gradeTask('repositoryUnderstanding', [outcome('a', 'answerAccuracy', true)]);
    expect(grade.metrics.map((metric) => metric.id)).toEqual(metricsForDimension('repositoryUnderstanding').map((spec) => spec.id));
    expect(grade.metrics.some((metric) => metric.id === 'churnRestraint')).toBe(false);
  });
});

describe('development task and suite validation', () => {
  const assertion = (fields: Partial<DevelopmentAssertion> = {}): DevelopmentAssertion => ({
    id: 'a1', purpose: 'probe', metric: 'implementationCorrectness', visibility: 'heldOut',
    predicate: { kind: 'containsPhrase', path: 'src/util/money.js', phrase: 'Math.round' },
    ...fields,
  });

  const editTask = (fields: Partial<DevelopmentTask> = {}): DevelopmentTask => makeDevelopmentTask({
    id: 'task.dev.edit.probe',
    suiteID: 'suite.cernum.development.multi-file-edit',
    suiteVersion: '1',
    dimension: 'multiFileEditing',
    kind: 'repositoryEdit',
    capabilityUnderTest: 'probe',
    fixtureRepoID: ledgerlite.id,
    fixtureRepoVersion: ledgerlite.version,
    fixtureRepoDigest: LEDGERLITE_DIGEST,
    prompt: { system: 'system', user: 'user' },
    requiredPaths: ['src/util/money.js', 'src/core/stages/round.js', 'test/cases/rounding.cases.json'],
    permittedPaths: ['CHANGELOG.md'],
    assertions: [assertion()],
    executionBudgetMilliseconds: 600_000,
    plannedRepetitions: 1,
    scoringContractID: DEVELOPMENT_SCORING_CONTRACT_ID,
    scoringContractVersion: DEVELOPMENT_SCORING_CONTRACT_VERSION,
    provenance: 'probe',
    tags: ['probe'],
    ...fields,
  });

  const suiteOf = (task: DevelopmentTask): DevelopmentSuite =>
    makeDevelopmentSuite(task.suiteID, task.suiteVersion, 'probe suite', task.dimension, [task]);

  const validate = (task: DevelopmentTask) => validateDevelopmentSuite(suiteOf(task), [ledgerlite]);

  it('accepts a well-formed multi-file-editing task', () => {
    expect(() => validate(editTask())).not.toThrow();
  });

  it('refuses a task a one-file patch could satisfy', () => {
    expect(MINIMUM_REQUIRED_FILES_FOR_MULTI_FILE_EDIT).toBe(3);
    expect(() => validate(editTask({ requiredPaths: ['src/util/money.js'] }))).toThrow(/does not measure this dimension/);
    expect(() => validate(editTask({ requiredPaths: ['src/util/money.js', 'test/cases/rounding.cases.json'] }))).toThrow(DevelopmentValidationFailure);
  });

  it('refuses a task whose every check is something the prompt already states', () => {
    expect(() => validate(editTask({ assertions: [assertion({ visibility: 'stated' })] })))
      .toThrow(/transcription rather than understanding/);
  });

  it('refuses a structural assertion attached to an executed metric', () => {
    expect(() => validate(editTask({ assertions: [assertion({ metric: 'newTestsPass' })] })))
      .toThrow(/masquerade as a test run/);
  });

  it('refuses a metric that belongs to the other dimension, and an unknown metric', () => {
    expect(() => validate(editTask({ assertions: [assertion({ metric: 'answerAccuracy' })] }))).toThrow(/belongs to repositoryUnderstanding/);
    expect(() => validate(editTask({ assertions: [assertion({ metric: 'conversation' })] }))).toThrow(/unknown metric/);
  });

  it('refuses a task sealed against a fixture digest the fixture no longer has', () => {
    expect(() => validate(editTask({ fixtureRepoDigest: 'mldr1:0000000000000000' })))
      .toThrow(/the fixture changed under a task that did not/);
  });

  it('refuses a task naming a fixture repository that is not registered', () => {
    expect(() => validate(editTask({ fixtureRepoID: 'fixture.repo.nope' }))).toThrow(/not registered/);
  });

  it('refuses an assertion naming a path that is in neither the fixture nor the task scope', () => {
    expect(() => validate(editTask({ assertions: [assertion({ predicate: { kind: 'fileExists', path: 'src/invented.js' } })] })))
      .toThrow(/neither in fixture repository/);
    // A required path that does not yet exist IS in scope: that is how "add this file" is expressed.
    expect(() => validate(editTask({
      requiredPaths: ['src/util/money.js', 'src/core/stages/round.js', 'test/cases/refunds.cases.json'],
      assertions: [assertion({ predicate: { kind: 'fileExists', path: 'test/cases/refunds.cases.json' } })],
    }))).not.toThrow();
  });

  it('refuses a scoring contract this engine does not register', () => {
    expect(() => validate(editTask({ scoringContractVersion: '2' }))).toThrow(/registers only/);
    expect(() => validate(editTask({ scoringContractID: 'contract.other' }))).toThrow(/registers only/);
  });

  it('refuses an empty prompt, a zero budget and zero repetitions', () => {
    expect(() => validate(editTask({ prompt: { system: '', user: 'u' } }))).toThrow(/empty prompt/);
    expect(() => validate(editTask({ executionBudgetMilliseconds: 0 }))).toThrow(/positive execution budget/);
    expect(() => validate(editTask({ plannedRepetitions: 0 }))).toThrow(/zero repetitions/);
  });

  it('holds a read-only task to exactly the reserved answer path', () => {
    const question = editTask({
      id: 'task.dev.question.probe', kind: 'repositoryQuestion', dimension: 'repositoryUnderstanding',
      suiteID: 'suite.cernum.development.repo-understanding',
      requiredPaths: [DEVELOPMENT_ANSWER_PATH], permittedPaths: [],
      assertions: [assertion({ metric: 'answerAccuracy', predicate: { kind: 'jsonHasPointer', path: DEVELOPMENT_ANSWER_PATH, pointer: '/file' } })],
    });
    expect(() => validate(question)).not.toThrow();
    expect(() => validate({ ...question, requiredPaths: ['src/index.js'] })).toThrow(/must require exactly/);
    expect(() => validate({ ...editTask(), requiredPaths: [...editTask().requiredPaths, DEVELOPMENT_ANSWER_PATH] }))
      .toThrow(/judged by what it did to the repository/);
  });

  it('refuses a fixture that already occupies the reserved answer path', () => {
    const colliding = makeFixtureRepo({
      ...ledgerlite,
      files: [...ledgerlite.files, { path: DEVELOPMENT_ANSWER_PATH, role: 'doc', contents: '{}' }],
    });
    const task = editTask({ fixtureRepoDigest: fixtureRepoDigest(colliding) });
    expect(() => validateDevelopmentSuite(suiteOf(task), [colliding])).toThrow(/reserved for a task/);
  });

  it('refuses duplicate task ids, a task outside its suite, and a dimension mismatch', () => {
    const task = editTask();
    expect(() => validateDevelopmentSuite({ ...suiteOf(task), tasks: [task, task] }, [ledgerlite])).toThrow(/duplicate development task id/);
    expect(() => validateDevelopmentSuite({ ...suiteOf(task), id: 'suite.other' }, [ledgerlite])).toThrow(/declares suite/);
    expect(() => validateDevelopmentSuite({ ...suiteOf(task), version: '9' }, [ledgerlite])).toThrow(/declares version/);
    expect(() => validateDevelopmentSuite({ ...suiteOf(task), dimension: 'repositoryUnderstanding' }, [ledgerlite]))
      .toThrow(/a rate nobody can read/);
    expect(() => validateDevelopmentSuite({ ...suiteOf(task), tasks: [] }, [ledgerlite])).toThrow(/declares no tasks/);
    expect(() => validateDevelopmentSuite(suiteOf({ ...task, assertions: [] }), [ledgerlite])).toThrow(/nothing would judge it/);
    expect(() => validateDevelopmentSuite(suiteOf({ ...task, assertions: [assertion(), assertion({ visibility: 'stated' })] }), [ledgerlite]))
      .toThrow(/twice/);
  });

  it('seals a task, and changes its identity when the contract version changes', () => {
    const task = editTask();
    expect(developmentTaskDigest(task)).toBe(developmentTaskDigest(makeDevelopmentTask({ ...task })));
    expect(developmentTaskDigest(task)).not.toBe(developmentTaskDigest({ ...task, prompt: { system: 's', user: 'different' } }));

    const key = developmentComparabilityKey(task);
    expect(key.startsWith('mldk1:')).toBe(true);
    expect(developmentComparabilityKey({ ...task, scoringContractVersion: '2' })).not.toBe(key);
    expect(developmentComparabilityKey({ ...task, fixtureRepoDigest: 'mldr1:other' })).not.toBe(key);

    const suite = suiteOf(task);
    expect(developmentSuiteDigest(suite).startsWith('mldsu1:')).toBe(true);
    expect(developmentSuiteDigest(suite)).not.toBe(developmentSuiteDigest({ ...suite, version: '2' }));
  });

  it('normalizes a task so two spellings of the same task seal alike', () => {
    const one = editTask({ tags: ['b', 'a', 'b'], permittedPaths: ['z', 'a', 'z'] });
    const two = editTask({ tags: ['a', 'b'], permittedPaths: ['a', 'z'] });
    expect(one.tags).toEqual(['a', 'b']);
    expect(one.permittedPaths).toEqual(['a', 'z']);
    expect(developmentTaskDigest(one)).toBe(developmentTaskDigest(two));
  });
});

describe('provenance', () => {
  const complete = {
    benchmarkVersion: '0.2.4', benchmarkCommit: 'abc1234', machineIdentifier: 'machine-1', platform: 'darwin',
    suiteID: 's', suiteVersion: '1', suiteDigest: 'mldsu1:x', taskID: 't', taskDigest: 'mldt1:x',
    comparabilityKey: 'mldk1:x', fixtureRepoID: 'f', fixtureRepoVersion: '1', fixtureRepoDigest: 'mldr1:x',
    contractID: 'c', contractVersion: '1', contractDigest: 'mldc1:x', executedAt: '2026-09-21T00:00:00Z',
  };

  it('accepts a complete record and names every field a partial one is missing', () => {
    expect(provenanceIsComplete(complete)).toEqual({ complete: true, missing: [] });
    expect(provenanceIsComplete({ ...complete, benchmarkCommit: '', machineIdentifier: '' }))
      .toEqual({ complete: false, missing: ['benchmarkCommit', 'machineIdentifier'] });
  });
});

describe('the development registry stays out of the text benchmark', () => {
  it('adds no suite to the sealed text catalog', () => {
    // These two numbers are pinned elsewhere against the parity corpus. Asserting them here as well
    // states the intent: a development suite must never arrive by being added to the text registry.
    expect(registeredSuites).toHaveLength(14);
    expect(allGovernedSuites.some((suite) => suite.id.raw.includes('development'))).toBe(false);
    expect(registeredSuites.some((suite) => suite.id.raw.includes('development'))).toBe(false);
  });

  it("adds no member to the text benchmark's capability dimensions", () => {
    for (const dimension of ALL_DEVELOPMENT_DIMENSIONS) {
      expect(ALL_DIMENSIONS as string[]).not.toContain(dimension);
    }
    expect(ALL_DIMENSIONS).toHaveLength(12);
  });
});
